from infrastructure.interfaces_impl.adressanderung_parser_interface_impl import AdressanderungParserInterface
from infrastructure.interfaces_impl.aufenthaltstitel_parser_interface_impl import AufenthaltstitelParserInterface
from infrastructure.interfaces_impl.eat_abholung_parser_interface_impl import eATAbholungParserInterface
from infrastructure.interfaces_impl.others_parser_interface_impl import OthersParserInterface
from infrastructure.interfaces_impl.registration_office_parser_interface_impl import RegistrationOfficeParserInterface

# termins_parser_interface = TerminsParserInterfaceImpl()


adressanderung_parser_interface = AdressanderungParserInterface()
eat_abholung_parser_interface = eATAbholungParserInterface()
registration_office_parser_interface = RegistrationOfficeParserInterface()
others_parser_interface = OthersParserInterface()
aufenthaltstitel_parser_interface = AufenthaltstitelParserInterface()
