from infrastructure.repositories_impl.category_of_termins_repositpry_impl import CategoryOfTerminsRepositoryImpl
from infrastructure.repositories_impl.termins_repository_impl import TerminsRepositoryImpl

termins_repository = TerminsRepositoryImpl()
category_of_termins_repository = CategoryOfTerminsRepositoryImpl()
